### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by eGorets** [suragch/mongol-library#1]
I couldn't run your project on Samsung and Xiaomi, but on Motorola and Nexus emulator it worked

```
07-11 13:07:49.344 27860 27860 E AndroidRuntime: FATAL EXCEPTION: main
07-11 13:07:49.344 27860 27860 E AndroidRuntime: Process: net.studymongolian.mongollibrarydemo, PID: 27860
07-11 13:07:49.344 27860 27860 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.studymongolian.mongollibrarydemo/net.studymongolian.mongollibrarydemo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "net.studymongolian.mongollibrarydemo.MainActivity" on path: DexPathList[[zip file "/data/app/net.studymongolian.mongollibrarydemo-2/base.apk"],nativeLibraryDirectories=[/data/app/net.studymongolian.mongollibrarydemo-2/lib/arm64, /system/lib64, /vendor/lib64]]
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.studymongolian.mongollibrarydemo.MainActivity" on path: DexPathList[[zip file "/data/app/net.studymongolian.mongollibrarydemo-2/base.apk"],nativeLibraryDirectories=[/data/app/net.studymongolian.mongollibrarydemo-2/lib/arm64, /system/lib64, /vendor/lib64]]
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
07-11 13:07:49.344 27860 27860 E AndroidRuntime: 	... 9 more
07-11 13:07:49.346  3713 18734 D Debug   : !@DumpState : SHIP
07-11 13:07:49.346  3713 18734 D Debug   : !@DumpState : debug level:0x4f4c
07-11 13:07:49.346  3713 18734 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
07-11 13:07:49.346  3713 18734 W ActivityManager:   Force finishing activity net.studymongolian.mongollibrarydemo/.MainActivity
```

**Comment by eGorets** [comment]
It worked on real Nexus and Samsung Galaxy SIII, but on the last one I got a crash on `MongolEditText` activity

```
   Caused by: java.lang.NullPointerException
                                                                                        at net.studymongolian.mongollibrary.MongolTextView.setPadding(MongolTextView.java:280)
```

**Comment by suragch** [comment]
I'm sorry. For some reason I didn't see your issue until just now. I've made quite a few changes since July. Are you still getting any crashes? On Xiaomi it is working ok for me.

**Comment by eGorets** [comment]
Hey man, we solved all issue in the past. We had some chatting in SO

**Comment by suragch** [comment]
Oh, OK. I had forgotten. Great, I'll close this now.
